### ISSUE TITLE
fixed point or binary input image

### ISSUE THREAD

**Issue by fabiovito** [kunglab/ebnn#5]
Is it possible change the net to use only fixed point or binary input?
Exclude floating point totally inner the binary net?
This permits to run this c example also in micro without FPU.

**Comment by BradMcDanel** [comment]
Yes -- this is a good suggestion and very possible. I will add an example with binary mnist.

**Comment by BradMcDanel** [comment]
I added [binary_mnist.h](https://github.com/kunglab/ebnn/blob/master/examples/binary_mnist.h) and [binary_mnist.c](https://github.com/kunglab/ebnn/blob/master/examples/binary_mnist.c) as an example using binary input. This does not replace the floating point operations for the Batchnorm layers, but otherwise only uses binary layers.
